### ISSUE TITLE
Create live game title link

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/PairPort#10]
The game title has no functionality. We need to turn the title element into a live link that should point to the main page of the game.

**Comment by vaxdr** [comment]
was wondering if I can be assigned this

**Comment by richardlara67** [comment]
Go for it

**Comment by vaxdr** [comment]
So the title on the bottom has to bring the user to the image in the background or to the difficulty and start a new game options?

**Comment by richardlara67** [comment]
There should be 3 pages in total. 

1) Rules and “How to play”
2) Actual game
3) Animation/celebration upon game completion 

I think the title link should direct the user back to the homepage/first page.
