### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/PairPort#13]
The current background is set to black in the main screen and blue "during" the game.

**Comment by richardlara67** [comment]
Background changed.

**Comment by mohtech** [comment]
Was my code right on this? I know I added the hex for black where it said background in the code but couldn’t check to see or was there no pull request for this either?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by richardlara67** [comment]
There was no pull request from either one of them.
