### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by richardlara67** [richardlara67/PairPort#8]
Create better documentation for the README.md

**Comment by pjeandel** [comment]
Hi ! I would love to contribute and take this issue, could you assign me please ?

**Comment by richardlara67** [comment]
You got it!

**Comment by mohtech** [comment]
Has pje updated the read me? Richard can you assign us all to everything ?

**Comment by richardlara67** [comment]
Yup, he edited the README. You can still add more if you feel it's needed.

I'll go ahead and assign the issues to everyone.

**Comment by mohtech** [comment]
Ok will do and thanks!

**Comment by richardlara67** [comment]
Any progress on this issue?

**Comment by mohtech** [comment]
Yes , I sent a pull request for you to see, I added instructions and worded it better so that it made more sense.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by richardlara67** [comment]
I don't see any Pull request from my end. Do you mind submitting a new pull request again?

**Comment by mohtech** [comment]
Try going on my page and checking my clone. I do remember actually sending two pull requests but I will re submit tonight as soon as I get off work brother.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
